// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8dZHG9xhTeZXIQxQcPrRp8B2Y8yQj2MU',
    appId: '1:532939065829:web:9ad23b8e24d7292685070c',
    messagingSenderId: '532939065829',
    projectId: 'citi-guide-47cf4',
    authDomain: 'citi-guide-47cf4.firebaseapp.com',
    storageBucket: 'citi-guide-47cf4.firebasestorage.app',
    measurementId: 'G-SJYDLJZPVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavtFH75Lg0R-zr7j_48sx3Y4LTR-iiIs',
    appId: '1:532939065829:android:2a82ac4116406c0085070c',
    messagingSenderId: '532939065829',
    projectId: 'citi-guide-47cf4',
    storageBucket: 'citi-guide-47cf4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv8CM8LZjUgZeVv4E-8BrED99CGW2lQWE',
    appId: '1:532939065829:ios:d2473dd94bfb4e3685070c',
    messagingSenderId: '532939065829',
    projectId: 'citi-guide-47cf4',
    storageBucket: 'citi-guide-47cf4.firebasestorage.app',
    iosClientId: '532939065829-c1ngokgr4pqkf032t07idfjhdm4e8en2.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv8CM8LZjUgZeVv4E-8BrED99CGW2lQWE',
    appId: '1:532939065829:ios:d2473dd94bfb4e3685070c',
    messagingSenderId: '532939065829',
    projectId: 'citi-guide-47cf4',
    storageBucket: 'citi-guide-47cf4.firebasestorage.app',
    iosClientId: '532939065829-c1ngokgr4pqkf032t07idfjhdm4e8en2.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8dZHG9xhTeZXIQxQcPrRp8B2Y8yQj2MU',
    appId: '1:532939065829:web:965292614cbb37a485070c',
    messagingSenderId: '532939065829',
    projectId: 'citi-guide-47cf4',
    authDomain: 'citi-guide-47cf4.firebaseapp.com',
    storageBucket: 'citi-guide-47cf4.firebasestorage.app',
    measurementId: 'G-MCVLGJWFTZ',
  );
}
